In [3]:
# Numpy: A data science library, for numerical python.
# Library in pyhton
# Scientific Calculation
# n-dimensional array as an object
# Linear algebra

In [4]:
import numpy as np

In [6]:
s = np.array([1, 2, 3, 4, 5])
s

array([1, 2, 3, 4, 5])

In [8]:
type(s)

numpy.ndarray

In [10]:
a = np.array([[1, 2, 3], 
            [10, 20, 30]])
a

array([[ 1,  2,  3],
       [10, 20, 30]])

In [12]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [15]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.linspace(1, 4, 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [17]:
np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [18]:
a = np.array([1, 2, 3])

In [19]:
a

array([1, 2, 3])

In [20]:
print(a.dtype)

int32


In [21]:
# Difference between numpy array and list
# array takes less memory compare to list
# array is fast compare to list
# aray is convinient, while list isn't

In [24]:
# array vs list memory allocation

l = range(1000)

import sys # to calculate size
a = 10
print(sys.getsizeof(a)) # size of int, memory allocated to a
print(sys.getsizeof(a)*len(l))

28
28000


In [27]:
s = np.arange(1000)
print(s.size*s.itemsize)

4000


In [28]:
# array vs list speed

import time
import sys

In [29]:
size = 1000000
l1 = range(size)
l2 = range(size)

467.30899810791016


In [30]:
n1 = np.arange(size)
n2 = np.arange(size)

start = time.time()
result = n1 + n2
print((time.time()-start)*1000)

71.98476791381836


In [31]:
# numpy operations

s = np.array([[1, 2, 3],
             [10, 20, 30]])
print(s.ndim) # dimensions of particular array

2


In [33]:
print(s.itemsize) #bytesize of each element

4


In [34]:
print(s.dtype) #datatype of array

int32


In [35]:
print(s.shape) #shape of array

(2, 3)


In [36]:
print(s.size) #total no. of elements

6


In [37]:
# reshape the array

s.reshape(3, 2)

array([[ 1,  2],
       [ 3, 10],
       [20, 30]])

In [38]:
s[0, 0] # first row, second column

1

In [39]:
s[0, 1]

2

In [40]:
s[0:, 1]

array([ 2, 20])

In [41]:
s[0:2, 1:]

array([[ 2,  3],
       [20, 30]])

In [42]:
s = np.array([[1, 2, 3, 4, 5], 
              [10, 20, 30, 40, 50]])
print(s.shape)
print(s[1, 2:4])

(2, 5)
[30 40]


In [43]:
s.min()

1

In [45]:
s.max()

50

In [46]:
s.sum()

165

In [47]:
print(np.sum(s, axis = 0)) # rows
print(np.sum(s, axis = 1)) # columns

[11 22 33 44 55]
[ 15 150]


In [48]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(x + y)

[[ 6  8]
 [10 12]]


In [49]:
print(np.add(x, y))

[[ 6  8]
 [10 12]]


In [50]:
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [51]:
s = np.arange(6)
s

array([0, 1, 2, 3, 4, 5])

In [53]:
s.reshape(3, 2)
print(s)

[0 1 2 3 4 5]


In [54]:
s = s.reshape(3, 2)
print(s)

[[0 1]
 [2 3]
 [4 5]]


In [55]:
np.reshape(s, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
np.reshape(s, 6)

array([0, 1, 2, 3, 4, 5])

In [58]:
print(s.flatten())

[0 1 2 3 4 5]


In [59]:
# Pandas
# Data Analysis
# Data Manipulation
# Cleaning data
# best suitable for tabular data - haterogenenous column types
# unlabled, statistical, time series, matrix area

In [60]:
import numpy as np
import pandas as pd
s = np.array(["S", "a", "h", "i", "l"])
p = pd.Series(s)
print(p)

0    S
1    a
2    h
3    i
4    l
dtype: object


In [61]:
# Pandas has indexes, numpy has not

In [62]:
s = pd.Series(np.random.random(5), index = ["a", "b", "c", "d", "e"])
print(s)

a    0.450453
b    0.217069
c    0.454562
d    0.425565
e    0.545934
dtype: float64


In [63]:
print(type(s))

<class 'pandas.core.series.Series'>


In [65]:
s.dtype

dtype('float64')

In [66]:
data = {"pi": 3.14, "e": 2.718}
print(data)
s = pd.Series(data)
print(s)

{'pi': 3.14, 'e': 2.718}
pi    3.140
e     2.718
dtype: float64


In [67]:
s = pd.Series(np.random.random(5))
print(s)

0    0.818414
1    0.832001
2    0.787322
3    0.683902
4    0.991320
dtype: float64


In [68]:
s[1]

0.8320011836519036

In [69]:
s[0]

0.8184141317069128

In [70]:
s[2]

0.7873223618701093

In [71]:
s[3]

0.683902085885008

In [72]:
s[1:3]

1    0.832001
2    0.787322
dtype: float64

In [74]:
print(s.index)

RangeIndex(start=0, stop=5, step=1)


In [75]:
print(s.ndim)

1


In [77]:
print(s.size)

5


In [78]:
print(s.shape)

(5,)
